#!/usr/bin/perl
# BSC to ads. Rewrites BSC data obtained from VIZIER to Ada array, converting sexagesimal to radians.
# NOTE BSC.dat was wrong at 7051 and 7539 - these are errors in the VIZIER. Fixed
# Call with ./BSCtoads.pl < BSC.dat > BSC.ads

print "with tcslib; use tcslib; -- make PI visible\n";
print "Package BSC is\n";
print "-- This file generated by BSCtoads.pl\n";

print "BSC_DATA : CATALOG(1 .. 9110) := (";

$count = 1;
while ($line = <>) {
   if ($count != 1) {print ",\n";}
   ($bsc, $rah, $ram, $ras, $decd, $decm, $decs, $mag, $rapm, $decpm) = split(" ", $line);

   if ($rah eq "") {
      print "(-1, 0.0, 0.0, 0.0, 0.0, 0.0)";
      next;
   }

   # save declination sign for infamous -00 sexagesimal disaster.
   if (substr($decd,0,1) eq '-') { $dec_sign = '-1.0' } else {$dec_sign='+1.0'}

   $decd_mag = substr($decd,1,3);

   print "($bsc, ($rah.0 + $ram.0/60.0 + $ras/3600.0)*PI/12.0, $dec_sign*($decd_mag.0 + $decm.0/60.0 + $decs.0/3600.0)*PI/180.0,";
   print " $rapm, $decpm, $mag)";
 
   $count = $count+1;
}
print ");\n";
print "end BSC;\n";
