#!/usr/bin/perl
# FK5 to ads. Rewrites FK5 data obtained from VIZIER to Ada array, converting sexagesimal to radians.
# Call with ./FK5toads.pl < FK5.dat > FK5.ads

print "with tcslib; use tcslib; -- make PI visible\n";
print "Package FK5 is\n";
print "-- This file generated by FK5toads.pl\n";

print "FK5_DATA : CATALOG(1..1670) := (";
$count = 1;
while ($line = <>) {
   if ($count != 1) {print ",\n";}
   ($fk5, $rah, $ram, $ras, $rapm, $decd, $decm, $decs, $decpm, $mag) = split(" ", $line);
   while ($count < $fk5 ) {
      print "(-1, 0.0, 0.0, 0.0, 0.0, 0.0),\n";
      $count = $count + 1;
   }
   # save declination sign for infamous -00 sexagesimal disaster.
   if (substr($decd,0,1) eq '-') { $dec_sign = '-1.0' } else {$dec_sign='+1.0'}

   $decd_mag = substr($decd,1,3);

   print "($fk5, ($rah.0 + $ram.0/60.0 + $ras/3600.0)*PI/12.0, $dec_sign*($decd_mag.0 + $decm.0/60.0 + $decs/3600.0)*PI/180.0,";
   print " $rapm, $decpm, $mag)";
 
   $count = $count+1;
}
print ");\n";
print "end FK5;\n";
