#!/usr/bin/perl
# IC to ads. Rewrites IC data obtained from VIZIER to Ada array, converting sexagesimal to radians.
# Call with ./ICtoads.pl < IC.dat > IC.ads

print "with tcslib; use tcslib; -- make PI visible\n";
print "Package IC is\n";
print "-- This file generated by ICtoads.pl\n";

print "IC_DATA : CATALOG(1..5386) := (";
$count = 1;
while ($line = <>) {
   if ($count != 1) {print ",\n";}
   ($n, $ngc, $star, $rah, $ram, $ras, $dec_sign, $decd, $decm, $decs, $mag) = split(" ", $line);

   if ($mag eq '') { $mag = '-99.99'}
   $dec_sign = $dec_sign . '1.0';
   print "($ngc, ($rah.0 + $ram.0/60.0 + $ras/3600.0)*PI/12.0, $dec_sign*($decd.0 + $decm.0/60.0 + $decs.0/3600.0)*PI/180.0,";
   print "0.0, 0.0, $mag)";
 
   $count = $count+1;
}
print ");\n";
print "end IC;\n";
