#!/usr/bin/perl
# MESSIER to ads. Rewrites MESSIER data obtained from KPNO to Ada array, converting sexagesimal to radians.
# Call with ./MESSIERtoads.pl < MESSIER.dat > MESSIER.ads
# Note M42 is wrong in KPNO - 37 mintues RA should be 35. Fixed.

print "with tcslib; use tcslib; -- make PI visible\n";
print "Package MESSIER is\n";
print "-- This file generated by MESSIERtoads.pl\n";

print "MESSIER_DATA : CATALOG(1..110) := (";
$count = 1;
while ($line = <>) {
   if ($count != 1) {print ",\n";}
   ($linenum, $ra,$dec, $epoch, $rapm, $decpm, $mag, $M, $mnum, $hash) = split(" ", $line);
     ($rah, $ram, $ras) = split(":", $ra); 
     ($decd, $decm, $decs) = split(":", $dec);

   # save declination sign for infamous -00 sexagesimal disaster.
   if (substr($decd,0,1) eq '-') { $dec_sign = '-1.0' } else {$dec_sign='+1.0'}

   $decd_mag = substr($decd,1,3);

   print "($mnum, ($rah.0 + $ram.0/60.0 + $ras/3600.0)*PI/12.0, $dec_sign*($decd_mag.0 + $decm.0/60.0 + $decs/3600.0)*PI/180.0,";
   print " 0.0, 0.0, $mag)";
 
   $count = $count+1;
}
print ");\n";
print "end MESSIER;\n";
