#!/usr/bin/perl
# NGC to ads. Rewrites NGC data obtained from VIZIER to Ada array, converting sexagesimal to radians.
# Call with ./NGCtoads.pl < NGC.dat > NGC.ads

print "with tcslib; use tcslib; -- make PI visible\n";
print "Package NGC is\n";
print "-- This file generated by NGCtoads.pl\n";

print "NGC_DATA : CATALOG(1 .. 7840) := (";
$count = 1;
while ($line = <>) {
   if ($count != 1) {print ",\n";}
   ($n, $ngc, $star, $rah, $ram, $ras, $dec_sign, $decd, $decm, $decs, $mag) = split(" ", $line);

   $dec_sign = $dec_sign . '1.0';

   print "($ngc,($rah.0 + $ram.0/60.0 + $ras/3600.0)*PI/12.0, $dec_sign*($decd.0 + $decm.0/60.0 + $decs.0/3600.0)*PI/180.0, 0.0, 0.0, ";

   if ($mag eq '') {print "-99.99)"} else{ print "$mag)"}
 
   $count = $count+1;
}
print ");\n";
print "end NGC;\n";
